app:
  host: "localhost"
  port: 8080

db_config:
  host: "localhost"
  dbname: "postgres"
  dbuser: "mayank"
  dbpassword: ""
  maxconnection: 30

logger:
  filename:   "app.log"
  max_size:    10
  max_age:     10
  max_backups: 10
  local_time:  false
  compress:   false
